"""
Skill Test Catalogue — M8

Hard-coded catalogue of available skills and their 20-question MCQ banks.
Each question has 4 options (index 0–3) and a correct_index.

We ship 25+ questions per skill so tests can be randomly sampled.
"""
from __future__ import annotations
import random
from typing import Any

# ── Types ──────────────────────────────────────────────────────────────────────

class Question:
    def __init__(self, text: str, options: list[str], correct_index: int):
        self.text          = text
        self.options       = options
        self.correct_index = correct_index

    def to_client_dict(self, index: int) -> dict:
        """Return question stripped of correct_index (for sending to client)."""
        return {
            "index":   index,
            "text":    self.text,
            "options": self.options,
        }

    def to_grading_dict(self, index: int) -> dict:
        """Full dict including correct_index (server-side only)."""
        return {
            "index":         index,
            "text":          self.text,
            "options":       self.options,
            "correct_index": self.correct_index,
        }


class SkillMeta:
    def __init__(self, key: str, label: str, description: str, icon: str, questions: list[Question]):
        self.key         = key
        self.label       = label
        self.description = description
        self.icon        = icon
        self.questions   = questions

    def sample_20(self) -> list[Question]:
        """Return 20 randomly-sampled questions (or all if fewer than 20)."""
        pool = list(self.questions)
        random.shuffle(pool)
        return pool[:20]


# ── Question Banks ─────────────────────────────────────────────────────────────

REACT_QUESTIONS = [
    Question("What hook is used to perform side effects in a React functional component?",
             ["useState", "useEffect", "useContext", "useReducer"], 1),
    Question("Which of the following correctly describes React's virtual DOM?",
             ["A direct copy of the browser DOM", "A lightweight in-memory representation of the DOM",
              "A server-side rendering technique", "A CSS-in-JS library"], 1),
    Question("What does JSX stand for?",
             ["JavaScript XML", "JavaScript Extension", "Java Syntax Extension", "JSON XML"], 0),
    Question("How do you pass data from a parent component to a child component in React?",
             ["Through state", "Through props", "Through context only", "Through refs"], 1),
    Question("What is the correct way to update state using useState?",
             ["state = newValue", "setState(newValue)", "const [value, setValue] = useState(); value = newValue", "const [value, setValue] = useState(); setValue(newValue)"], 3),
    Question("Which hook would you use to avoid expensive re-calculations on every render?",
             ["useCallback", "useMemo", "useRef", "useLayoutEffect"], 1),
    Question("What does the key prop in a list help React do?",
             ["Style list items", "Identify which items changed/added/removed", "Add accessibility", "Sort the list"], 1),
    Question("What is the purpose of React.StrictMode?",
             ["Enforce TypeScript types", "Enable production optimisations", "Highlight potential problems in development", "Prevent all side effects"], 2),
    Question("When does useEffect run with an empty dependency array []?",
             ["On every render", "Only on unmount", "Only once after the initial render", "Never"], 2),
    Question("What is prop drilling?",
             ["Optimising props for performance", "Passing props through many layers of components", "Drilling for data with GraphQL", "Creating circular prop dependencies"], 1),
    Question("How do you prevent a child component from re-rendering when its parent re-renders?",
             ["React.memo", "React.PureComponent", "shouldComponentUpdate in a class component", "All of the above"], 3),
    Question("What is the Context API primarily used for?",
             ["Routing", "Global state management avoiding prop drilling", "Async data fetching", "Styling"], 1),
    Question("Which lifecycle method does useEffect with a cleanup function replace?",
             ["componentDidMount only", "componentWillUnmount only", "Both componentDidMount and componentWillUnmount", "componentDidUpdate only"], 2),
    Question("What does React.lazy() enable?",
             ["Lazy state initialisation", "Code splitting / dynamic imports", "Deferred rendering", "Memoisation"], 1),
    Question("What is a controlled component?",
             ["A component with its own internal state", "A component whose form input value is controlled by React state", "A component that controls its children", "A memoised component"], 1),
    Question("Which hook gives you a mutable reference that persists across renders without triggering re-renders?",
             ["useState", "useMemo", "useRef", "useCallback"], 2),
    Question("What is the correct way to conditionally render a component?",
             ["if/else outside JSX only", "Ternary operator or && inside JSX", "switch statement inside JSX", "You cannot conditionally render in React"], 1),
    Question("What does the useReducer hook return?",
             ["state and dispatch", "state and setState", "reducer and action", "state and action"], 0),
    Question("What is a React fragment used for?",
             ["Performance optimisation", "Grouping elements without adding an extra DOM node", "Error boundaries", "Code splitting"], 1),
    Question("How do you handle errors in a React component tree?",
             ["try/catch inside render", "Error boundaries (class components with componentDidCatch)", "useError hook", "window.onerror"], 1),
    Question("What does the second argument to useEffect (the dependency array) control?",
             ["When cleanup runs", "When the effect re-runs", "The order of effects", "Whether effects are async"], 1),
    Question("What is reconciliation in React?",
             ["Server-side rendering", "The process by which React updates the DOM to match the virtual DOM", "State synchronisation", "Context propagation"], 1),
    Question("Which event handler naming convention does React use?",
             ["lowercase (onclick)", "camelCase (onClick)", "PascalCase (OnClick)", "snake_case (on_click)"], 1),
    Question("What is the difference between state and props?",
             ["No difference", "State is mutable and internal; props are immutable and passed in", "Props are internal; state is external", "State is for classes; props are for functions"], 1),
    Question("What is React Suspense used for?",
             ["Error handling", "Data fetching and lazy loading with a fallback UI", "Animation", "Context injection"], 1),
]

PYTHON_QUESTIONS = [
    Question("What is the output of: print(type([]))?",
             ["<class 'tuple'>", "<class 'list'>", "<class 'array'>", "<class 'dict'>"], 1),
    Question("Which keyword is used to define a generator function?",
             ["return", "yield", "generate", "async"], 1),
    Question("What does the GIL stand for in CPython?",
             ["Global Instance Lock", "Global Interpreter Lock", "Generic Import Layer", "General I/O Library"], 1),
    Question("What is the difference between a list and a tuple in Python?",
             ["Lists are ordered; tuples are not", "Tuples are mutable; lists are immutable", "Lists are mutable; tuples are immutable", "No difference"], 2),
    Question("Which of these is NOT a valid Python data type?",
             ["float", "complex", "char", "bytes"], 2),
    Question("What does *args in a function signature allow?",
             ["Keyword-only arguments", "Variable number of positional arguments", "Default arguments", "Type annotations"], 1),
    Question("What is a decorator in Python?",
             ["A design pattern for UI", "A function that wraps another function to modify its behaviour", "A type of class method", "A comment style"], 1),
    Question("What will `list(range(0, 10, 2))` return?",
             ["[0,1,2,3,4,5,6,7,8,9]", "[0,2,4,6,8]", "[2,4,6,8,10]", "[0,2,4,6,8,10]"], 1),
    Question("What does `__init__` do in a Python class?",
             ["Imports the module", "Initialises a new instance of the class", "Defines class-level constants", "Destroys the object"], 1),
    Question("Which built-in function returns the number of items in a list?",
             ["count()", "size()", "len()", "length()"], 2),
    Question("What is a list comprehension?",
             ["A way to document lists", "A concise way to create lists from iterables", "A sorting algorithm", "A list slice"], 1),
    Question("What does `with open('file.txt') as f:` do?",
             ["Opens a file and automatically closes it when the block exits", "Opens a file permanently", "Creates a file", "Reads a file into a string"], 0),
    Question("What is the difference between `==` and `is` in Python?",
             ["No difference", "== checks value equality; is checks identity (same object)", "is checks value; == checks identity", "is is only for strings"], 1),
    Question("Which module provides regular expressions in Python?",
             ["regex", "re", "regexp", "pattern"], 1),
    Question("What does `enumerate()` return?",
             ["A list of values", "An iterator of (index, value) tuples", "A dictionary", "A sorted list"], 1),
    Question("What is the purpose of `__str__` in a class?",
             ["String type checking", "Return a human-readable string representation of the object", "Convert strings to the class type", "Import string utilities"], 1),
    Question("What does `lambda` create?",
             ["A class", "An anonymous function", "A generator", "A coroutine"], 1),
    Question("What is the difference between `append()` and `extend()` on a list?",
             ["No difference", "append adds one item; extend adds all items from an iterable", "extend adds one item; append adds from an iterable", "append is for strings; extend is for lists"], 1),
    Question("Which statement about Python's `None` is correct?",
             ["None equals 0", "None equals False", "None is a singleton object of type NoneType", "None and null are the same"], 2),
    Question("What is the purpose of `__name__ == '__main__'`?",
             ["Check if the file is a module", "Run code only when the script is executed directly, not imported", "Define the main class", "Set the module name"], 1),
    Question("What does `zip()` do?",
             ["Compress files", "Aggregate elements from multiple iterables into tuples", "Merge dictionaries", "Sort two lists together"], 1),
    Question("What is a Python virtual environment used for?",
             ["Running Python in the browser", "Isolating project dependencies", "Speeding up execution", "Cross-platform compatibility"], 1),
    Question("How do you handle exceptions in Python?",
             ["try/catch", "try/except", "try/error", "catch/throw"], 1),
    Question("What does `@property` allow you to do?",
             ["Add metadata to a class", "Define a method that is accessed like an attribute", "Make a method static", "Override __init__"], 1),
    Question("What is the difference between `deepcopy` and `copy` (shallow copy)?",
             ["No difference", "copy duplicates the outer object; deepcopy recursively duplicates all nested objects", "deepcopy is faster", "copy is for lists; deepcopy is for dicts"], 1),
]

NODEJS_QUESTIONS = [
    Question("What is the event loop in Node.js?",
             ["A for loop over events", "The mechanism that handles async callbacks and I/O operations", "An HTTP event system", "A loop that blocks the thread"], 1),
    Question("Which module system does Node.js originally use?",
             ["AMD", "ESModules", "CommonJS (require/module.exports)", "UMD"], 2),
    Question("What does `process.env` provide?",
             ["CPU environment stats", "Environment variables", "Node.js version info", "File system paths"], 1),
    Question("What is the purpose of `package.json`?",
             ["A JSON config for the OS", "Project metadata and dependency manifest", "A compiled output file", "A runtime configuration"], 1),
    Question("What does `npm install --save-dev` do?",
             ["Installs globally", "Installs as a production dependency", "Installs as a development dependency", "Saves a backup"], 2),
    Question("How do you create an HTTP server in Node.js?",
             ["http.createServer()", "new Server()", "express.create()", "server.listen()"], 0),
    Question("What is middleware in Express.js?",
             ["A database layer", "Functions that have access to req, res, and next in the request-response cycle", "A templating engine", "A caching layer"], 1),
    Question("What does `async/await` replace in Node.js?",
             ["Callbacks and promise chains", "Synchronous code", "Streams", "Events"], 0),
    Question("What is the purpose of `require.resolve()`?",
             ["Import a module", "Return the file path that require() would load", "Check if a module is installed", "Reload a cached module"], 1),
    Question("Which of the following is a Node.js stream type?",
             ["Observable", "Readable", "Subscribable", "Iterable"], 1),
    Question("What does `cluster` module provide?",
             ["Database clustering", "Child processes sharing server ports to utilise multi-core CPUs", "Load balancing across servers", "Message queues"], 1),
    Question("What is the difference between `setImmediate` and `setTimeout(fn, 0)`?",
             ["No difference", "setImmediate fires after I/O callbacks; setTimeout after timers phase", "setTimeout is always faster", "setImmediate is deprecated"], 1),
    Question("How do you read a file synchronously in Node.js?",
             ["fs.read()", "fs.readFileSync()", "fs.readSync()", "io.readFile()"], 1),
    Question("What does `EventEmitter` allow you to do?",
             ["Emit DOM events", "Create and listen to custom events", "Handle HTTP events", "Manage child processes"], 1),
    Question("What is `body-parser` middleware used for?",
             ["Parsing cookies", "Parsing incoming request bodies (JSON, URL-encoded)", "Logging requests", "Compressing responses"], 1),
    Question("What does `process.exit(1)` indicate?",
             ["Successful exit", "Exit with an error code", "Exit and restart", "Exit and run cleanup"], 1),
    Question("What is the purpose of `__dirname` in Node.js?",
             ["The directory of the running user", "The absolute path of the current module's directory", "The root of the project", "The Node.js installation directory"], 1),
    Question("What does `npm run build` do?",
             ["Installs packages", "Executes the build script defined in package.json scripts", "Compiles Node.js source", "Creates a Docker image"], 1),
    Question("What is a Buffer in Node.js?",
             ["A network buffer", "A fixed-size allocation in memory for handling binary data", "A stream buffer", "A cache for HTTP responses"], 1),
    Question("How does Node.js achieve non-blocking I/O?",
             ["Multiple threads", "Libuv's async I/O and the event loop", "Web Workers", "GPU acceleration"], 1),
    Question("What does `res.json()` do in Express?",
             ["Parses request JSON", "Sends a JSON response and sets Content-Type to application/json", "Validates JSON", "Converts objects to strings"], 1),
    Question("What is the purpose of `dotenv`?",
             ["Pretty-print JSON", "Load environment variables from a .env file into process.env", "Generate .env files", "Validate env var types"], 1),
    Question("What does `Promise.all()` do?",
             ["Run promises sequentially", "Run promises in parallel and resolve when all resolve (or reject if any reject)", "Retry failed promises", "Cancel pending promises"], 1),
    Question("What is CORS and why does it matter in Node.js APIs?",
             ["A caching standard", "Cross-Origin Resource Sharing — controls which origins can access the API from browsers", "A compression format", "A Node.js security module"], 1),
    Question("What does `morgan` do in an Express application?",
             ["Authentication middleware", "HTTP request logging middleware", "Rate limiting", "Body parsing"], 1),
]

SQL_QUESTIONS = [
    Question("Which SQL clause filters rows after grouping?",
             ["WHERE", "HAVING", "FILTER", "LIMIT"], 1),
    Question("What does a LEFT JOIN return?",
             ["Only matching rows", "All rows from the left table and matching rows from the right", "All rows from both tables", "Only non-matching rows"], 1),
    Question("What is a primary key?",
             ["The first column of a table", "A unique, non-null identifier for each row", "A foreign key reference", "An indexed column"], 1),
    Question("What does the DISTINCT keyword do?",
             ["Sorts results", "Removes duplicate rows from the result set", "Counts unique values", "Filters NULL values"], 1),
    Question("Which aggregate function returns the number of rows?",
             ["SUM()", "AVG()", "COUNT()", "MAX()"], 2),
    Question("What is a foreign key?",
             ["A key that can't be null", "A column that references the primary key of another table", "An encrypted key", "A composite key"], 1),
    Question("What does EXPLAIN / EXPLAIN ANALYZE do?",
             ["Explains a stored procedure", "Shows the query execution plan", "Documents a table schema", "Validates SQL syntax"], 1),
    Question("What is a database index used for?",
             ["Storing backups", "Speeding up data retrieval operations", "Enforcing uniqueness", "Both B and C"], 3),
    Question("Which normal form eliminates transitive dependencies?",
             ["1NF", "2NF", "3NF", "BCNF"], 2),
    Question("What does a CROSS JOIN produce?",
             ["All matching rows", "The Cartesian product of both tables", "Only unique rows", "A union of both tables"], 1),
    Question("What is a CTE (Common Table Expression)?",
             ["A type of index", "A temporary named result set defined with WITH, used in a query", "A stored procedure", "A view"], 1),
    Question("What does COALESCE() do?",
             ["Combines two columns", "Returns the first non-NULL value from a list", "Counts NULL values", "Converts types"], 1),
    Question("What is the difference between UNION and UNION ALL?",
             ["No difference", "UNION removes duplicates; UNION ALL keeps all rows including duplicates", "UNION ALL removes duplicates", "UNION is for different column types"], 1),
    Question("What does a window function (OVER clause) allow?",
             ["Aggregate across the whole table", "Calculations across a set of rows related to the current row without collapsing them", "Create sub-queries", "Define partitions"], 1),
    Question("What is the purpose of ACID in databases?",
             ["A query language", "Atomicity, Consistency, Isolation, Durability — properties guaranteeing reliable transactions", "A schema type", "An indexing strategy"], 1),
    Question("What does the IS NULL operator check for?",
             ["Empty strings", "Zero values", "Missing/null values", "Undefined columns"], 2),
    Question("Which SQL statement modifies existing rows?",
             ["INSERT", "UPDATE", "ALTER", "MERGE"], 1),
    Question("What is a composite key?",
             ["A key that is encrypted", "A primary key made up of two or more columns", "A foreign key referencing multiple tables", "An auto-incremented key"], 1),
    Question("What does TRUNCATE do compared to DELETE?",
             ["They are identical", "TRUNCATE removes all rows faster without logging individual row deletions; DELETE is logged row by row", "DELETE is faster", "TRUNCATE can use a WHERE clause"], 1),
    Question("What is a subquery?",
             ["A stored procedure", "A query nested inside another query", "A view alias", "A JOIN shorthand"], 1),
    Question("What does GROUP BY do?",
             ["Sorts rows", "Groups rows with the same values so aggregate functions can be applied", "Filters rows", "Joins tables"], 1),
    Question("What is referential integrity?",
             ["Data type consistency", "Ensuring foreign key values match existing primary key values", "Index consistency", "Null constraint enforcement"], 1),
    Question("What does ROW_NUMBER() window function return?",
             ["The total row count", "A unique sequential integer for each row within a partition", "The rank with gaps", "The position in the full table"], 1),
    Question("What is the difference between CHAR and VARCHAR?",
             ["No difference", "CHAR is fixed-length; VARCHAR is variable-length", "VARCHAR is faster", "CHAR supports Unicode; VARCHAR does not"], 1),
    Question("What does a database trigger do?",
             ["Schedules a query", "Automatically executes a function in response to INSERT/UPDATE/DELETE events on a table", "Logs slow queries", "Creates an index"], 1),
]

TYPESCRIPT_QUESTIONS = [
    Question("What is TypeScript?",
             ["A JavaScript runtime", "A statically-typed superset of JavaScript that compiles to JavaScript", "A CSS preprocessor", "A testing framework"], 1),
    Question("What does the `interface` keyword define?",
             ["A class implementation", "A contract specifying the shape of an object", "An abstract class", "A module"], 1),
    Question("What is the difference between `type` and `interface` in TypeScript?",
             ["No difference", "type can represent primitives and unions; interface is for object shapes and supports declaration merging", "interface supports generics; type does not", "type is for functions; interface is for objects"], 1),
    Question("What does `unknown` represent compared to `any`?",
             ["They are the same", "unknown requires type narrowing before use; any bypasses all type checking", "any is stricter than unknown", "unknown is deprecated"], 1),
    Question("What is a generic in TypeScript?",
             ["A base class", "A type parameter that allows functions/classes to work with multiple types", "A utility type", "A type alias"], 1),
    Question("What does the `readonly` modifier do?",
             ["Makes a class abstract", "Prevents reassignment of a property after initialisation", "Marks optional properties", "Makes a type nullable"], 1),
    Question("What is the purpose of `tsconfig.json`?",
             ["Define project dependencies", "Configure the TypeScript compiler options", "Define type definitions", "Configure tests"], 1),
    Question("What does `Partial<T>` do?",
             ["Makes all properties of T required", "Makes all properties of T optional", "Picks a subset of T", "Removes nullable properties"], 1),
    Question("What is a union type?",
             ["Combining two interfaces", "A type that can be one of several types (A | B)", "A type that must satisfy multiple types", "A type intersection"], 1),
    Question("What does the `as` keyword do in TypeScript?",
             ["Imports a module alias", "Type assertion — tells the compiler to treat a value as a specific type", "Creates a type alias", "Casts numbers"], 1),
    Question("What are declaration files (.d.ts)?",
             ["Test specification files", "TypeScript source compiled to declarations", "Files containing only type information for JavaScript libraries", "Configuration files"], 2),
    Question("What does `ReturnType<T>` utility type do?",
             ["Infers the return type of a function type T", "Defines a function's return type", "Makes return type optional", "Unwraps a Promise return type"], 0),
    Question("What is strict mode in TypeScript?",
             ["A runtime check", "A set of stricter compiler flags including strictNullChecks and noImplicitAny", "Prettier formatting", "A lint rule set"], 1),
    Question("What does the `never` type represent?",
             ["A null value", "Values that never occur (exhausted union, function that never returns)", "An optional value", "An empty array"], 1),
    Question("What is `keyof` used for?",
             ["Iterating object keys at runtime", "Creating a union type of all keys of an object type", "Indexing into arrays", "Defining enum keys"], 1),
    Question("What does `Pick<T, K>` do?",
             ["Removes keys K from T", "Creates a type with only the specified keys K from T", "Maps over T's keys", "Requires K keys in T"], 1),
    Question("What is an enum in TypeScript?",
             ["A union type", "A set of named constants", "A mapped type", "A generic constraint"], 1),
    Question("What does `Record<K, V>` create?",
             ["An array of V", "An object type with keys of type K and values of type V", "A Map object", "A Set of keys"], 1),
    Question("What does `infer` do in conditional types?",
             ["Adds runtime inference", "Captures and names a type within a conditional type expression", "Infers generics from arguments", "Replaces type assertions"], 1),
    Question("What does `Exclude<T, U>` do?",
             ["Removes U from T's properties", "Creates a type by removing types assignable to U from T (union subtraction)", "Intersects T and U", "Picks U from T"], 1),
    Question("What is a tuple type in TypeScript?",
             ["An immutable array", "An array with fixed length and known types at each position", "A named array", "A readonly array"], 1),
    Question("What does the optional chaining operator `?.` do?",
             ["Checks for null only", "Safely accesses nested properties, returning undefined instead of throwing if nullish", "Is a TypeScript-only feature", "Replaces optional parameters"], 1),
    Question("What is a discriminated union?",
             ["A union with unique member names", "A union where each member has a common literal type field used as a discriminant for narrowing", "A union of interfaces", "An exhaustive union"], 1),
    Question("What does `Required<T>` do?",
             ["Makes all properties of T optional", "Makes all properties of T required (removes optionality)", "Adds required validators", "Marks T as non-nullable"], 1),
    Question("What is the purpose of `satisfies` operator (TS 4.9+)?",
             ["A type assertion that widens types", "Validates an expression satisfies a type while inferring the most precise type", "Replaces as assertions", "A runtime check"], 1),
]

DOCKER_QUESTIONS = [
    Question("What is a Docker image?",
             ["A running container", "A read-only template used to create containers", "A virtual machine", "A Dockerfile"], 1),
    Question("What does `docker-compose up` do?",
             ["Builds images only", "Starts all services defined in docker-compose.yml", "Stops all containers", "Pulls latest images"], 1),
    Question("What is the purpose of a Dockerfile?",
             ["A runtime config", "Instructions for building a Docker image", "A compose spec", "A health check script"], 1),
    Question("What does `EXPOSE` in a Dockerfile do?",
             ["Opens a firewall port", "Documents that the container listens on a port (doesn't actually publish)", "Publishes a port to the host", "Exposes env variables"], 1),
    Question("What is the difference between `COPY` and `ADD` in a Dockerfile?",
             ["No difference", "COPY is a simple file copy; ADD can extract tar archives and fetch URLs", "ADD is newer and replaces COPY", "COPY supports remote URLs"], 1),
    Question("What does `docker volume` provide?",
             ["Temporary storage", "Persistent storage that survives container restarts", "Network isolation", "Image layers"], 1),
    Question("What is a multi-stage build in Docker?",
             ["Running multiple containers", "Using multiple FROM statements to produce a smaller final image", "Building for multiple platforms", "Parallel build steps"], 1),
    Question("What does `.dockerignore` do?",
             ["Ignores Dockerfile syntax errors", "Excludes files from the build context sent to the Docker daemon", "Hides secrets from images", "Configures image layers"], 1),
    Question("What is the difference between CMD and ENTRYPOINT?",
             ["No difference", "ENTRYPOINT sets the fixed executable; CMD provides default arguments that can be overridden", "CMD is for scripts; ENTRYPOINT for binaries", "CMD runs as root; ENTRYPOINT as user"], 1),
    Question("What does `docker exec -it <container> bash` do?",
             ["Restarts the container", "Opens an interactive bash shell in a running container", "Builds and runs a container", "Logs into a registry"], 1),
    Question("What is a Docker network used for?",
             ["Disk I/O", "Enabling communication between containers", "Image distribution", "Port mapping"], 1),
    Question("What does the `--rm` flag do when running a container?",
             ["Removes the image", "Automatically removes the container when it exits", "Forces a restart", "Removes volumes"], 1),
    Question("What is Docker Hub?",
             ["A Docker CLI tool", "A public registry for Docker images", "A container orchestrator", "A Docker monitoring tool"], 1),
    Question("What does `HEALTHCHECK` in a Dockerfile define?",
             ["A security scan", "A command Docker runs to check if the container is healthy", "An alerting rule", "A build-time test"], 1),
    Question("What is the purpose of `ARG` in a Dockerfile?",
             ["Runtime environment variable", "Build-time variable that can be passed with --build-arg", "Container argument", "A secret"], 1),
    Question("What does `docker ps` show by default?",
             ["All containers (running and stopped)", "Only running containers", "All images", "Container logs"], 1),
    Question("What is a container registry?",
             ["A container log store", "A service for storing and distributing Docker images", "A Kubernetes component", "An image cache"], 1),
    Question("What does `docker build -t myapp:latest .` do?",
             ["Runs a container named myapp", "Builds an image from the current directory and tags it myapp:latest", "Pulls myapp:latest from Docker Hub", "Tags an existing image"], 1),
    Question("What is the default restart policy for a container?",
             ["always", "on-failure", "no (never restart)", "unless-stopped"], 2),
    Question("What does `docker logs <container>` do?",
             ["Opens a shell", "Shows the stdout/stderr output of a container", "Shows system logs", "Shows build logs"], 1),
    Question("What is the purpose of `ENV` in a Dockerfile?",
             ["Build arguments", "Sets environment variables that persist in the image and running containers", "Exports variables to the host", "Declares secrets"], 1),
    Question("What does `docker system prune` do?",
             ["Removes all images", "Removes stopped containers, unused networks, dangling images, and build cache", "Removes volumes only", "Removes running containers"], 1),
    Question("What is a dangling image?",
             ["An image with no tag", "An untagged image that is no longer referenced by any container", "A corrupted image", "An image with no layers"], 1),
    Question("What does `depends_on` in docker-compose.yml do?",
             ["Sets resource limits", "Declares service start-order dependencies", "Links services together at runtime", "Merges service configs"], 1),
    Question("What is the purpose of a Docker overlay network?",
             ["Connecting containers on the same host", "Enabling cross-host container communication in a Swarm", "Encrypting container traffic", "Replacing host networking"], 1),
]

GRAPHQL_QUESTIONS = [
    Question("What is GraphQL?",
             ["A graph database query language", "A query language for APIs with a type system, where clients specify exactly what data they need", "A REST extension", "A NoSQL interface"], 1),
    Question("What is a GraphQL schema?",
             ["A database schema", "The type definitions that describe the API's data and operations", "A JSON config", "A client-side cache"], 1),
    Question("What are the three root operation types in GraphQL?",
             ["GET, POST, DELETE", "Query, Mutation, Subscription", "Read, Write, Stream", "Query, Update, Subscribe"], 1),
    Question("What is the N+1 problem in GraphQL?",
             ["Sending N queries for N users", "Resolvers triggering N database queries for N related items instead of one batched query", "Returning N extra fields", "Pagination with N items"], 1),
    Question("What does DataLoader solve?",
             ["Schema stitching", "The N+1 query problem by batching and caching database calls per request", "Federation", "Mutation validation"], 1),
    Question("What is a resolver in GraphQL?",
             ["An error handler", "A function that returns the data for a field in the schema", "A middleware", "A caching layer"], 1),
    Question("What are GraphQL fragments?",
             ["Code-splitting units", "Reusable selections of fields that can be spread into multiple queries", "Inline queries", "Schema extensions"], 1),
    Question("What does `__typename` return in a GraphQL response?",
             ["The schema version", "The type name of the object at that position in the response", "The resolver name", "The parent type name"], 1),
    Question("What is introspection in GraphQL?",
             ["Logging resolver calls", "Querying the schema itself to discover types, fields, and directives", "Validating queries at build time", "Schema migration"], 1),
    Question("What is schema stitching / federation?",
             ["Merging two schemas at runtime", "Composing multiple independent GraphQL services into one unified graph", "A caching strategy", "Splitting a large schema into files"], 1),
    Question("What does a GraphQL subscription do?",
             ["Watches for HTTP poll changes", "Provides real-time data push over a persistent connection (WebSocket)", "Subscribes to an RSS feed", "Registers a webhook"], 1),
    Question("What is an `input` type in GraphQL?",
             ["The request body", "A special type used for mutation arguments that only allows scalar and other input types", "A query parameter", "A response type"], 1),
    Question("What does the `@deprecated` directive do?",
             ["Removes a field from the schema", "Marks a field as deprecated in the schema, visible in introspection", "Hides a field from queries", "Logs usage"], 1),
    Question("What is persisted queries?",
             ["Saving GraphQL queries in the database", "Sending a hash instead of the full query text to reduce request size and improve security", "Caching query results", "Compiling queries at build time"], 1),
    Question("What does `null` in a non-nullable field (`String!`) propagation mean?",
             ["The field defaults to an empty string", "Null bubbles up to the nearest nullable parent, potentially nulling entire sub-trees", "An error is silently swallowed", "The response returns 400"], 1),
    Question("What is the purpose of GraphQL variables?",
             ["Schema documentation", "Passing dynamic values to queries/mutations without string interpolation", "Default field values", "Caching keys"], 1),
    Question("What is a union type in GraphQL?",
             ["A type that combines two scalar types", "A type that can be one of several object types, resolved with __resolveType", "A merged interface", "A polymorphic scalar"], 1),
    Question("What is the difference between a Union and an Interface in GraphQL?",
             ["No difference", "Interface defines common fields; Union can hold types with no shared fields", "Union requires __resolveType; Interface does not", "Interface is client-side only"], 1),
    Question("What is Apollo Client primarily used for?",
             ["A GraphQL server", "A state management and data fetching library for GraphQL clients", "Schema generation", "A GraphQL gateway"], 1),
    Question("What does `extend type Query` do in schema definition?",
             ["Overrides the Query type", "Adds additional fields to the Query type across files/modules", "Deprecates existing queries", "Creates a sub-schema"], 1),
]

# ── Skill Catalogue ────────────────────────────────────────────────────────────

SKILL_CATALOGUE: dict[str, SkillMeta] = {
    "react": SkillMeta(
        key="react", label="React", icon="⚛️",
        description="Modern React including hooks, context, performance optimisation, and component patterns.",
        questions=REACT_QUESTIONS,
    ),
    "python": SkillMeta(
        key="python", label="Python", icon="🐍",
        description="Core Python: data types, OOP, generators, decorators, async, and the standard library.",
        questions=PYTHON_QUESTIONS,
    ),
    "nodejs": SkillMeta(
        key="nodejs", label="Node.js", icon="🟢",
        description="Node.js runtime, Express, async patterns, streams, modules, and deployment.",
        questions=NODEJS_QUESTIONS,
    ),
    "sql": SkillMeta(
        key="sql", label="SQL", icon="🗄️",
        description="Relational databases: queries, joins, aggregates, window functions, and schema design.",
        questions=SQL_QUESTIONS,
    ),
    "typescript": SkillMeta(
        key="typescript", label="TypeScript", icon="🔷",
        description="TypeScript type system: generics, utility types, advanced patterns, and compiler configuration.",
        questions=TYPESCRIPT_QUESTIONS,
    ),
    "docker": SkillMeta(
        key="docker", label="Docker", icon="🐳",
        description="Containerisation with Docker: images, Dockerfiles, compose, volumes, networks.",
        questions=DOCKER_QUESTIONS,
    ),
    "graphql": SkillMeta(
        key="graphql", label="GraphQL", icon="◈",
        description="GraphQL API design: schemas, resolvers, queries, mutations, subscriptions, and tooling.",
        questions=GRAPHQL_QUESTIONS,
    ),
}


def get_skill(key: str) -> SkillMeta | None:
    return SKILL_CATALOGUE.get(key)


def get_all_skills() -> list[dict]:
    return [
        {
            "key":         s.key,
            "label":       s.label,
            "icon":        s.icon,
            "description": s.description,
            "question_count": len(s.questions),
        }
        for s in SKILL_CATALOGUE.values()
    ]
